
# The output directory for all generated files
out: ./doc

# True to clean the output directory before generation
# (recommended as it ensures no orphaned files from previous builds)
clean: true

# Only include public and protected members
publicOnly: true

# Whether to include externally declared inherited members
importedMembers: false

# Information about the project.  By default these will be taken
# from the assembly information of the first assembly.  Uncomment
# and update the following lines to override
# project:
#     name: MyProject
#     version: 1.9

# The assemblies for which documentation should be generated, 
# .xml files are expected in the same location
assemblies:
  - ./Build/Release/Topten.RichTextKit/netcoreapp2.1/Topten.RichTextKit.dll

# Namespaces to assumed when formatting fully qualified type names
namespaces:
  - System
  - System.Collections.Generic
  - System.Threading.Tasks

# The template and content files to be processed/copied
content:
  - src: LosAngeles
#  - del: /index.cshtml
#  - src: ./readme.md
#    dst: /index.md
#  - src: /path/to/your/logo.png
#    dst: /static/
#  - src: /path/to/your/icon.png
#    dst: /static/
#  - src: /path/to/your/license.md
#    dst: /

# Optional links to be shown in the header
# headers:
#   - text: Your Site
#     href: http://www.yoursite.com

# Optional links to be shown in the footer
# footers:
#   - text: GitHub
#     href: http://github.com/yourcompany/yourproject
#   - text: License
#     href: /license.html

# Optional logo to be shown in header
# logo:
#     image: /static/logo.png
#     href: /index.html

# Smaller logo to be shown in header
# icon:
#     image: /static/icon.png
#     href: /index.html

# Optional entries to go at the top of the table of contents
#toc:
#  - text: Getting Started
#    href: .
#    subItems:
#      - text: Introduction
#        href: .

# Optional arbitary data that will be available to templates 
# via the `Settings.Data` property
# data:
#     anything: you like can go here

data:
  projectUrlPrefix: "/richtextkit/"