
# The output directory for all generated files
out: ./doc

# True to clean the output directory before generation
# (recommended as it ensures no orphaned files from previous builds)
clean: true

# Only include public and protected members
publicOnly: true

# Whether to include externally declared inherited members
importedMembers: false

# Information about the project.  By default these will be taken
# from the assembly information of the first assembly.  Uncomment
# and update the following lines to override
project:
    name: RichTextKit
#     version: 1.9

# The assemblies for which documentation should be generated, 
# .xml files are expected in the same location
assemblies:
  - ./Build/Release/Topten.RichTextKit/netcoreapp2.1/Topten.RichTextKit.dll

# Namespaces to be assumed when formatting fully qualified type names
namespaces:
  - System
  - System.Collections.Generic
  - System.Threading.Tasks

# The template and content files to be processed/copied
content:
  - src: LosAngeles
  - dst: /index.md
  - src: ./docsrc/
  - src: ./Artwork/banner@2x.png
    dst: /Artwork/
  

# Optional entries to go at the top of the table of contents
toc:
  - text: Guides
    href: .
    subItems:
      - text: Introduction
        href: .
      - text: Getting Started
        href: gettingStarted
      - text: Creating a TextBlock
        href: createTextBlock
      - text: Rendering Text
        href: rendering
      - text: Measuring Text
        href: measuring
      - text: Bidirectional Text
        href: bidi
      - text: Text Limits
        href: limits
      - text: Hit Testing
        href: hittesting
      - text: Styles
        href: styles
      - text: License
        href: license


# Optional data to pass to template
data:
  projectUrlPrefix: "/richtextkit/"